[tool.poetry]
name = "se"
version = "0.1.0"
description = ""
authors = ["Iván Molina Rebolledo <ivan@ivmoreau.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
Jinja2 = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
